
/* Copyright (c) 2021 Hasebe Masahiko. Released under the MIT license */

#ifndef msgf_h
#define msgf_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define MAX_PART_NUM 1

#define MAX_BUFFER_SIZE 1024

#define SAMPLING_FREQ 44100.0

#define AUDIO_FRAME_PER_CONTROL 128

#define MAX_TONE_COUNT 3

typedef struct Msgf Msgf;